### ISSUE TITLE
Data appears lately in admin panel.

### ISSUE THREAD

**Issue by stgleb** [mrjoes/flask-admin#15]
Hello, im using Flask-Admin==1.3.0.

I', displaying data from different datasources:

admin.add_view(MyModelView(Token, session=Session()))
admin.add_view(MyModelView(LoginAttempt, session=Session()))
admin.add_view(MyModelView(Device, session=Session()))
admin.add_view(MyModelView(DeviceInfo, session=Session()))
admin.add_view(MyModelView(HCUser, session=Session()))
admin.add_view(MyModelView(Config, session=Session()))
admin.add_view(MyModelView(Report, session=CouponSession()))
admin.add_view(MyModelView(File, session=CouponSession()))

admin.add_view((MyModelView(User, db.session)))
admin.add_view((MyModelView(Role, db.session)))

And i wonder why some data, like token or device appears in admin panel with big latency.
Is it problem of SQLAlchemy session or something else?

**Comment by mrjoes** [comment]
What do you mean by "appeared with big latency"? You don't see data in the list view and have to refresh few times?

**Comment by stgleb** [comment]
It is not an issue of refresh. I can see it after some time, even when i refresh page each second. 
or when i restart app. So could you give me a hint why it appears after some time interval?

**Comment by stgleb** [comment]
It seems there is a problem with session management. Dont you think so?

**Comment by mrjoes** [comment]
Why do you create separate session for each view? You need to create single scoped session (http://docs.sqlalchemy.org/en/latest/orm/contextual.html) and pass it to view constructors.

**Comment by stgleb** [comment]
Thanks, i will try!

**Comment by stgleb** [comment]
Seems the problem  is still there.

**Comment by mrjoes** [comment]
Make sure you close session at the end of each request with Session.remove()

**Comment by stgleb** [comment]
yeah, but how should i do that?
Now i use sessions like this:

admin.add_view(MyModelView(Token, session=model_session))
admin.add_view(MyModelView(LoginAttempt, session=model_session))
admin.add_view(MyModelView(Device, session=model_session))
admin.add_view(MyModelView(DeviceInfo, session=model_session))
admin.add_view(MyModelView(HCUser, session=model_session))
admin.add_view(MyModelView(Config, session=model_session))
admin.add_view(MyModelView(Report, session=coupon_session))
admin.add_view(MyModelView(File, session=coupon_session))

But where in admin panel code should i do Session.remove()?

**Comment by mrjoes** [comment]
You have to add Flask hook:

``` python
def close_db_connection(sender, **extra):
    Session.remove()

from flask import request_tearing_down
request_tearing_down.connect(close_db_connection, app)
```

See more here: http://flask.pocoo.org/docs/0.10/signals/

**Comment by stgleb** [comment]
still doesnt help((
