### ISSUE TITLE
Customise fields in form_ajax_refs

### ISSUE THREAD

**Issue by karimtabet** [mrjoes/flask-admin#3]
Hi,

Do we know if Admin supports customising the fields of a model in form_ajax_refs?

I've opened a stackoverflow question regarding what I'm after specifically: https://stackoverflow.com/questions/31139948/flask-admin-custom-queryajaxmodelloader

Thanks!

**Comment by mrjoes** [comment]
Flask-Admin was moved to its own organization: https://github.com/flask-admin/flask-admin/

But I wrote comment on StackOverflow website as well. Hope it helps.
