### ISSUE TITLE
Flask-Admin doesn't populates correct value from Enum column

### ISSUE THREAD

**Issue by citizen-stig** [mrjoes/flask-admin#33]
I have a working example here: https://github.com/citizen-stig/flask_admin_enum

I investigated it a little bit and maybe problem is in SQLalchemy and how it provides information about Enum column.

**Comment by russel** [comment]
@citizen-stig Did this bug get fixed? I am trying to edit a database using Flask-Admin but every time I try and edit a a row, the edit dialogue gets the default enum values not the ones in the row. The test and string entries are fine, but if I can't edit sensibly the enum columns, I will have to, well, panic.

**Comment by citizen-stig** [comment]
I don't know, I see that last release in [official repo](https://github.com/flask-admin/flask-admin/releases) was in june, so I believe it is not.

But I did a following workaround:
```import enum
from flask_admin.contrib.sqla import ModelView
from flask_admin.form.fields import Select2Field

class MyEnum(enum.Enum):
    category1 = 'category1'
    category2 = 'category2'

class EnumSelect2Field(Select2Field):
    def pre_validate(self, form):
        for v, _ in self.choices:
            if self.data == self.coerce(v):
                break
        else:
            raise ValueError(self.gettext('Not a valid choice'))


class InvoiceAdminView(ModelView):
    form_extra_fields = {
        'myenum': EnumSelect2Field(
            choices=[(x.name, x.name.title()) for x in MyEnum],
            coerce=MyEnum,
            default=MyEnum.choice1.name)}
```

**Comment by russel** [comment]
I shall give this a go, thanks.

Given this is still a problem I think the issue here should remain open even if it is an SQLAlchemy problem. Having it open, helps people find workarounds for problems such as this.

**Comment by citizen-stig** [comment]
This issue is closed because it is not main repo.
Please check https://github.com/flask-admin/flask-admin

**Comment by russel** [comment]
Now don't I look like a person who fails to notice the obvious.  :-)

Did this issue get transferred to there?

**Comment by citizen-stig** [comment]
Yes, there's an issue: https://github.com/flask-admin/flask-admin/issues/1315

**Comment by russel** [comment]
Hummm… I wonder why my Google search found this one but no sign of that one. Weird. But then I can now go to the right place to moan. Thanks for posting this problem, it is a complete blocker for me. I am not sure the workarounds are actually going to work…but it will be tried.

**Comment by russel** [comment]
@citizen-stig  FYI The code above isn't working for me as is, and I haven't got a variant to work yet, still working on it…
