### ISSUE TITLE
ARRAY not editable with SQLAlchemy >= 1.1.0

### ISSUE THREAD

**Issue by marcoesposito1988** [mrjoes/flask-admin#36]
A change in SQLAlchemy 1.1.0 broke postgres ARRAY fields (I don't know about other databases).

Using Flask-Admin 1.4.2 and SQLAlchemy 1.1.0 results into the ARRAY field not showing in the edit form. Downgrading to SQLAlchemy 1.0.0 resolves the issue for me.

I will submit a pull request if I find a solution.

See:
http://docs.sqlalchemy.org/en/latest/changelog/changelog_11.html#change-1.1.0b2-postgresql

**Comment by citizen-stig** [comment]
Please note, that this is not main repo. This repo has all up to date information: https://github.com/flask-admin/flask-admin

**Comment by marcoesposito1988** [comment]
Oh, right, thanks! I will open the issue there if necessary.
