### ISSUE TITLE
Computed field

### ISSUE THREAD

**Issue by litnimax** [mrjoes/flask-admin#5]
I have a question on how to implement a computed field.

For example, I'd like to add such a field to column_list, smth like that:

```
class UserProfile(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.Unicode(128))
    admin = db.Column(db.Boolean, index=True)

   def get_name_ex(self):
        return '%s (admin: %s)' % (self.name, self.admin)

...
class UserProfileAdmin(ModelView, AuthBaseView):
    column_list = ['get_name_ex']
```

But this does not work as expected. 
Please advise.

**Comment by mrjoes** [comment]
Make it a property, either generic python one or a SQLAlchemy hybrid property.

**Comment by litnimax** [comment]
Hm.. Tried to make a propery. Will try again.
Also found probably a solution with column_formatters - http://www.paulsprogrammingnotes.com/2014/03/checkmark-columnformatters-flask-admin.html
Thanks.

**Comment by litnimax** [comment]
No need for a property in my case - just format a column like here http://stackoverflow.com/questions/17174707/can-model-views-in-flask-admin-hyperlink-to-other-model-views
Thanks.
Please close it.
