### ISSUE TITLE
Raising on multiple-column properties

### ISSUE THREAD

**Issue by garaden** [mrjoes/flask-admin#575]
Some of our SQLA models have composite properties, which make Flask-Admin raise when scaffold_list_columns or scaffold_form runs. We were able to work around it by subclassing ModelView, but would it make sense to just `continue` on these properties instead of raising? Due to the nature of composite properties, I don't think anyone would expect to see them in the admin interface anyway.

**Comment by nitishr** [comment]
I see you have a TODO to skip and add a warning. Would you accept a PR replacing the TypeError with a warning?

**Comment by mrjoes** [comment]
Sure!

**Comment by nitishr** [comment]
Just submitted a new PR with a change to form.py as well. With this change, you no longer need to ignore them explicitly through column_exclude_list and form_excluded_columns.

**Comment by nitishr** [comment]
Apologize, but my first fix wasn't complete actually. Simply warning doesn't actually fix any problem, but replaces the earlier TypeError with another TypeError. So, I've not updated the code to continue in case of a multi-column field to skip it. This merge should actually fix the problem in both view.py and form.py
