### ISSUE TITLE
On model change

### ISSUE THREAD

**Issue by psykzz** [mrjoes/flask-admin#576]
Could we provide the previous model around here
https://github.com/mrjoes/flask-admin/blob/1a62fce5307f986285ffa2bf9825fa3f5d47d34e/flask_admin/contrib/sqla/view.py#L819

Using SQLA as an example but yeh can we get a before and after for models so we do a comparison.
Im currently looking to provide some audit logs using this method and do this was changed between them.

**Comment by xqliu** [comment]
I also would like to see this feature in flask-admin, that's not only valuable for audit of model changes, but also is needed if we would like to control whether a model can be edit on a specific state(for example, if field status is "COMPLETE", then all delete/update operation will be denied.

I think that's kind of a very handy feature.

**Comment by mrjoes** [comment]
You can control it by overriding edit view and checking if model can be edited before calling parent view. In addition to that you can override list template and show/hide pencil icon based on your logic.
