### ISSUE TITLE
Not localization menu item

### ISSUE THREAD

**Issue by Panter7777** [mrjoes/flask-admin#751]
Hello, in my app admin view
admin = Admin(app)
admin.add_view(ModelView(User, db.session, name=_(u'Пользователи')))

and when I change the locale from ru to en (?lang=en), all changed but not my menu item

**Comment by mrjoes** [comment]
You need to use lazy text wrapper, https://pythonhosted.org/Flask-Babel/#flask.ext.babel.lazy_gettext
