### ISSUE TITLE
Idea: Editable List View

### ISSUE THREAD

**Issue by pawl** [mrjoes/flask-admin#755]
It would be useful to be able to bulk edit records from the list view, like this:
![editable_listview2](https://cloud.githubusercontent.com/assets/992533/5567370/15760168-8f09-11e4-959d-a2f170ff0f5e.png)

I've made some progress on getting the form fields to show on the list view:
https://github.com/pawl/flask-admin/compare/list_editable

However, I'm having trouble with wtform's FieldList and processing the submitted data. Is there a way to do this that uses the existing inline form code? Or, does anyone have any suggestions for how to implement this?

Here's the gist I've been using to test my branch (with a new column_editable_list property): https://gist.github.com/pawl/ec6c51d1a10ffa75bac3

**Comment by gordol** [comment]
Nice! I have been working on something very similar but using gevent socketio to push changes in real-time to other connected clients as well. Good stuff!

**Comment by gordol** [comment]
Nice! I have been working on something very similar but using gevent socketio to push changes in real-time to other connected clients as well. Good stuff!

**Comment by gordol** [comment]
Found one minor UI issue...

http://node.gordo4.com/snaps/37e652d9f501d90df8e156bdecda1e1e.png

**Comment by gordol** [comment]
Perhaps bump down default number of textarea rows from 7 to say... 4 or 5.

**Comment by gordol** [comment]
https://vitalets.github.io/x-editable/docs.html#textarea

**Comment by karimtabet** [comment]
I've been having an issue using this when my tables primary key is a UUID with a "-" character. It seems to only read a sub-string of the UUID; from the beginning of the UUID to the first "-" character.

The bottom of the stack trace is:
```
  DataError: (DataError) invalid input syntax for uuid: "edcda51d"
  LINE 3: WHERE products.product_uuid = 'edcda51d'
                                      ^
'SELECT products.product_uuid AS products_product_uuid, products.title AS products_title,      products.short_description AS products_short_description, products.long_description AS products_long_description, products.last_seen AS products_last_seen, products.price AS products_price, products.rating AS products_rating \nFROM products \nWHERE products.product_uuid = %(param_1)s' {'param_1': u'edcda51d'}
```
The UI goes a bit crazy too:
https://i.imgur.com/vAAUMzB.png

**Comment by pawl** [comment]
The issue is here: https://github.com/flask-admin/flask-admin/blob/a964d3fff65ebbc8ab31ea4f8c3e8be1a5b9b296/flask_admin/model/fields.py#L146

We can probably do some escaping here to make it work: https://github.com/flask-admin/flask-admin/blob/a964d3fff65ebbc8ab31ea4f8c3e8be1a5b9b296/flask_admin/model/fields.py#L158

**Comment by mrjoes** [comment]
@pawl There's helper for that.

https://github.com/flask-admin/flask-admin/blob/master/flask_admin/tools.py#L110 - pass enumerable, it'll serialize as a string.

https://github.com/flask-admin/flask-admin/blob/master/flask_admin/tools.py#L122 - pass string, get `list`.

**Comment by karimtabet** [comment]
@mrjoes Can you explain how the helper might be used to bypass this issue with the "-" character?

**Comment by mrjoes** [comment]
@karimtabet it encodes/decodes lists to/from string and handles escaping. 

So instead of concatenating strings like here: https://github.com/flask-admin/flask-admin/blob/a964d3fff65ebbc8ab31ea4f8c3e8be1a5b9b296/flask_admin/model/fields.py#L158

You can use helper to encode this tuple and then instead of using `split` - you can get your list back.

@pawl linked snippets that should be changed.

Unfortunately I didn't have time to make the change and test it.

**Comment by pawl** [comment]
@karimtabet I submitted the pull request with the fix, can you test it from my branch?

Run this command to pip install from my branch:
```
pip install -e git+https://github.com/pawl/flask-admin.git@fix_editable_pk2#egg=flask-admin
```

**Comment by karimtabet** [comment]
@pawl I've had a little test run and it all works as expected. Good work! I'll keep testing the branch and will let you know if I notice any issues.
