### ISSUE TITLE
what if the url of my app server is something like: http://www.company.com/app

### ISSUE THREAD

**Issue by litaotao** [mrjoes/flask-admin#761]
if my admin is defined as 
```
admin = admin.Admin(app, name='Example: PyMongo')
```
And our company url is http://www.company.com, and each products of our company can be accessed by http://www.company.com/app_name.

And I want to add a admin page for my app, my app can be access by :  
http://www.company.com/my_app_name

how can I access the admin page by typing 
http://www.company.com/my_app_name/admin

currently, it seems that I can only access the page by:

http://www.company.com/admin

---  

thanks, I read the source code, and there are two parameters in the Admin class, url and subdomain, but seems not working when I defined these two parameters.

**Comment by pawl** [comment]
Can you try using?:
```
admin = admin.Admin(app, name='Example: PyMongo', url='/my_app_name')
```
