### ISSUE TITLE
Editing model breaks relationships

### ISSUE THREAD

**Issue by iamale** [mrjoes/flask-admin#776]
For example, let's define models called Country and City like this:

```py
class Country(db.Model):
  id = db.Column(db.Integer, primary_key=True)
  name = db.Column(db.String(80))

class City(db.Model):
  id = db.Column(db.Integer, primary_key=True)
  country_id = db.Column(db.Integer, db.ForeignKey('country.id'))
  country = db.relationship('Country',
      backref=db.backref('cities', lazy='dynamic'))
```

And the view:

```py
class CountryView(AuthMixin, MyModelViewMixin, ModelView):
  form_rules = ['name']
             # We don't want to display cities here, as there might be tons of them
```

Now if we try to edit a country, every city that used to be connected to the country now loses the relationship. Is there any way to work this around?

**Comment by mrjoes** [comment]
Yes, don't use `form_rules`, but use `form_columns`. 

Why it is happening:
1. Flask-Admin creates wtforms form with all model fields
2. `form_rules` only controls how fields are displayed, leaving form as is
3. Browser sends only single field (name) upon form submit, wtform assumes that relation is empty and resets it

**Comment by iamale** [comment]
This worked, thanks!
