### ISSUE TITLE
fileadmin IndexError when browsing subdirectories

### ISSUE THREAD

**Issue by ptxmac** [mrjoes/flask-admin#779]
Browsing a subdirectory raises an exception: IndexError: tuple index out of range
This is because of fileadmin.py line 474 where it's trying to format the timestamp to a date, but the first row in the items are inserted at line 458 and doesn't contain a timestamp: `items.append(('..', parent_path, True, 0))`

**Comment by kawaikunee** [comment]
I've got the same error. Pls, give me some recipe as soon as possible.

**Comment by donniemattingly** [comment]
If you edit line 458 to be `items.append(('..',parent_path,True,0,0))` that should resolve the issue.

**Comment by pawl** [comment]
Looks like this was fixed already: https://github.com/mrjoes/flask-admin/commit/cbbae4c300466556aff287d2e26c7d9051c4683b

**Comment by ptxmac** [comment]
Oh perfect! Then we just need to wait for a new release :)
