### ISSUE TITLE
lost self-existent translations when upgrade flask-admin to 1.0.9

### ISSUE THREAD

**Issue by shnode** [mrjoes/flask-admin#788]
when upgrade to flask-admin 1.0.9, found that the flask-admin self-existent  transaltion all lost.

though I can translate my own word use `lazy_gettext` py file or `_gettext` in template.

in vision like this(things in `template/model/list.html` remain English)：

![image](https://cloud.githubusercontent.com/assets/7784713/6062213/ef6a639e-ad88-11e4-8a1b-fdfaf9a9fbe1.png)

what should I do ? @pawl  @mrjoes

**Comment by pawl** [comment]
Is this for zh_Hans or zh_Hant? If yes, those were fixed after 1.0.9 in this pull request: https://github.com/mrjoes/flask-admin/pull/754

Try installing flask-admin with this command:
```
pip install -e git+https://github.com/mrjoes/flask-admin.git#egg=flask-admin
```

![hant](https://cloud.githubusercontent.com/assets/992533/6074409/490e2a30-ad83-11e4-8d73-5dd683f08c5b.png)

**Comment by shnode** [comment]
I'm sorry this was a bit awkward that I can't use such command:

    pip install -e git+https://github.com/mrjoes/flask-admin.git#egg=flask-admin
    zsh: no matches found: git+https://github.com/mrjoes/flask-admin.git#egg=flask-admin

**Comment by pawl** [comment]
Does it work when you put it in quotes?: pip install -e 'git+
https://github.com/mrjoes/flask-admin.git#egg=flask-admin'

**Comment by shnode** [comment]
Awesome! Thanks a million！！
