### ISSUE TITLE
Can't update model with required file field

### ISSUE THREAD

**Issue by iurisilvio** [mrjoes/flask-admin#791]
It does not work because the file field is empty when I update the field. The current file name is shown in another text input, so it triggers the required validator.

**Comment by mrjoes** [comment]
Quick question - it is about wtforms `FileField` or custom Flask-Admin upload field?

Because if it is about `FileField`, then required validator won't work - there's no submitted file and validator will raise validation exception.

**Comment by iurisilvio** [comment]
It is the Flask-Admin field: `flask.ext.admin.form.FileUploadField`.

**Comment by iurisilvio** [comment]
I'm overriding my `"field"` this way in my `ModelView`:

```python
form_overrides = {
    'field': form.FileUploadField
}
```
