### ISSUE TITLE
Pagination on SQLServer

### ISSUE THREAD

**Issue by jjdenis** [mrjoes/flask-admin#8]
Hello !!

I'm using flask_admin version 1.3.0 on windows, with flaskalchemy and SQLServer, and I get the first page of the views right, but when I try to go to any other I get this error:

sqlalchemy.exc.CompileError
CompileError: MSSQL requires an order_by when using an OFFSET or a non-simple LIMIT clause

Thanks a lot for this awesome tool!!

**Comment by mrjoes** [comment]
Try adding default sort to your views with `column_default_sort`. MSSQL does not like OFFSET and LIMIT without ORDER BY.

**Comment by jjdenis** [comment]
Works like a charm. THANK YOU!!!

**Comment by oceanpad** [comment]
can not work for me, how did you add column_default_sort to model class?
