### ISSUE TITLE
Separate list view for models filtered by foreign key id

### ISSUE THREAD

**Issue by warmspringwinds** [mrjoes/flask-admin#801]
I am stuck with this problem:
http://stackoverflow.com/questions/28815655/flask-admin-separate-view-for-models-filtered-by-foreign-key
I didn't find any solutions in documentation.
Later I can contribute to documentation regarding this issue.

**Comment by pawl** [comment]
You need to override get_query and get_count_query: ‎readthedocs.org/en/latest/api/mod_contrib_sqla/#flask.ext.admin.contrib.sqla.ModelView.get_query                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          From: warmspringwindsSent: Tuesday, March 3, 2015 5:43 AMTo: mrjoes/flask-adminReply To: mrjoes/flask-adminSubject: [flask-admin] Separate list view for models filtered by foreign key id (#801)I am stuck with this problem:
http://stackoverflow.com/questions/28815655/flask-admin-separate-view-for-models-filtered-by-foreign-key
I didn't find any solutions in documentation.
Later I can contribute to documentation regarding this issue.

—Reply to this email directly or view it on GitHub.

**Comment by warmspringwinds** [comment]
Thank you for your reply.

Yes, this the way to solve it if you have a filtering criteria that doesn't change.

I've posted the solution on SO. I am not sure whether or not it is the best way to solve this problem.
