### ISSUE TITLE
uuid primary key field not shown in edit form, even though added in form_columns

### ISSUE THREAD

**Issue by mensurm** [mrjoes/flask-admin#818]
I'm using SQLAlchemy. My Model has a uuid field as the primary key. It is not shown in the edit form, even though I have added the field name in form_columns. I can display it in the list view, by adding it to the columns_list. I have tried this with other models which have, for instance, string as primary key, and the field is  shown on the form. However, in the case of models which have uuid field as primary key, this field is not displayed.

**Comment by mrjoes** [comment]
Most likely it is happening because Flask-Admin ModelConverter does not know how to handle UUID data type and can't figure out which wtforms field to use.

You can use customized ModelConverter instance and support this data type though.

**Comment by mensurm** [comment]
I did a bit of a workaround in the end, just added the primary key field to the the form_extra_fields dictionary.

**Comment by pawl** [comment]
This will be fixed by #1155
