### ISSUE TITLE
Add view without adding into the header

### ISSUE THREAD

**Issue by italomaia** [mrjoes/flask-admin#835]
Hi folks. Today I needed to add a modelview to admin without adding it to the admin header. My goal is to use the header only for custom views, like reports. This would be a nice feature.

**Comment by pawl-rs** [comment]
Look for this "is_visible" method in the docs: flask_admin.base.BaseView.is_visible

Assuming you mean menu when you say header - you can remove items from the menu by having is_visible return false.

**Comment by italomaia** [comment]
Thanks! That's about it.
